[book]
title = "Opinionated Hugo: A Guide for the Rest of Us"
authors = ["Kenneth Bowen"]
language = "en"
multilingual = false
src = "src"

[output.html]
git-repository-url = https://github.com/kpb/opinionated-hugo
